### PR TITLE
Can we delete CoC?

### PR DESCRIPTION
**Pull request by Visgean**
This is the worst code of conduct I have ever seen. It does not solve any real issues, it is not enforced, and overall you would break it about 50 times in normal one hour conversation about technology.

### CODE REVIEW

**Comment by neanias** [comment]
We wrote this based mainly on what he had observed in #compsoc on IRC, rather than IRL conversations

**Comment by CraigSnowden** [comment]
I assume the comment referring to breaking the code of conduct during the course of normal conversation refers to the “being nice” part, not the discrimination. It’s somewhat concerning that you’d consider trolling or “well-actuallys” part of a normal technology conversation. In my experience, it can make people quite uncomfortable, and rarely persuades someone of your viewpoint.

**Comment by jaidmin** [comment]
Which part exactly do you break 50 times in one hour of normal conversation?

**Comment by Visgean** [comment]
> In my experience, it can make people quite uncomfortable, and rarely persuades someone of your viewpoint.

Whats wrong with making people uncomfortable (not saying that it should be the goal but i think that should definitely be allowed.)

**Comment by Visgean** [comment]
And I was mostly referring to "Fanboy-ism. Just because Programming Language X has feature Y doesn't mean everyone who doesn't use it is making the biggest mistake of their lives." I had a lot of conversation comparing for example java / python. A lot of them has been useful and taught me new facts. 

Sure that it would be better if people would argue in more constructive manner but this is not encouraging such behaviour but rather silences the people who do it.

**Comment by jsren** [comment]
> Well-actuallys
> Fanboy-ism
> Feigned surprise

These are all far too specific, and frankly there's absolutely nothing wrong with them. Well actually you're saying that nobody here loves Compsoc as much as I do??

I'm assuming you mean "well-actuallys" when used to bully and patronise or humiliate people. And equally for "feigned surprise". In which case why not just say no bullying or patronising comments?

Creating a community which welcomes newcomers and promotes productive discussion is challenging and requires more than just matching conversations to some regex.

If you're not actively using the CoC and if (as it looks) there's contention over it, I would personally agree with its removal, as I don't see it does anything useful in addition to the University's code of conduct.

**Comment by neanias** [comment]
We do actually use the CoC in IRC and IRC-connected chat rooms. That was what it was initially drawn up for, where the University CoC jurisdiction doesn't necessarily reach. At a meeting of CompSoc, EUSA and University rules will more generally apply.

**Comment by Visgean** [comment]
Even for IRC there rules still makes little sense.

**Comment by neanias** [comment]
Really?

**Comment by jsren** [comment]
@neanias Perhaps make its restriction to IRC clearer then? And also it may be more productive to describe the community which the CompSoc IRC wishes to create and the aims of the CoC, rather than just saying "be nice".

I see why you have these examples - for new users who may not understand the impact of their comments on others. But I personally feel that in that case, the examples of misconduct are actually too broad, and showing _how_ specific examples of "well actually" and fanboy-isms can patronise others and attack others opinions and start undesired flame wars may better communicate what you mean.

I don't think it's a good thing that an initial response to finding this document is the submission of a PR to remove it!

**Comment by neanias** [comment]
@jsren, the description of the repo is 'The Code of Conduct for IRC (and bridged networks)'. Is that not already clear what it is designed for? I understand suggesting describing how we want CompSoc forums to be in terms of culture, but we also wanted a quick and simple way to indicate how people should act. It was initially going to be 'don't be a dick', but that was vetoed in favour of 'be nice'. (I'm still in favour of having it be 'don't be a meanie Tweenie', but that's just me.)

Generally, when this Code of Conduct is being invoked, members of the channel then try to ease the conflict and educate the parties on where they have gone wrong and how to do better.

**Comment by Visgean** [comment]
> the description of the repo is 'The Code of Conduct for IRC (and bridged networks)'.

this is only in description and not in the document itself.

> It was initially going to be 'don't be a dick', but that was vetoed in favour of 'be nice'. (I'm still in favour of having it be 'don't be a meanie Tweenie', but that's just me.)

I think that would have been better. I dont have problem with saying people should be nice, but the examples are just weird.

**Comment by jsren** [comment]
@neanias 

1) Not with #3, no. And "it's in the repo description" does not necessarily have a bearing on whether it should also be in the document itself.
2)
> we also wanted a quick and simple way to indicate how people should act. It was initially going to be 'don't be a dick'

For a CoC to exist just to say "don't be a dick", or indeed "be nice", is silly.
3) What you're saying then is that the CoC is not intended to be a preventative measure, to inform people of the rules of communication within the community. What's the point then?

R.E. #3  This might be fun to have for the IRC, but imo this shouldn't be a public document - if I'm being completely honest to me it looks quite immature.

**Comment by Boltovnya** [comment]
I believe the idea behind the CoC within Compsoc is when contentious topics come up, they can be discussed diplomatically and sensibly - rather than becoming the sort of discussion you find on imageboards. 

When people aggressively argue for language X over language Y, it can become, for lack of a better phrase, a s**t flinging contest. In these situations, the conversation becomes exclusionary to those who do want to get involved and in turn ruins the community spirit of Compsoc and its associated chat rooms.

Outlining specific examples is a good method of enforcing better behaviours for discussion, and I don't agree that this should change. 

> What you're saying then is that the CoC is not intended to be a preventative measure, to inform people of the rules of communication within the community. What's the point then?

Codes of conduct are a way of informing new people on how they should expect to conduct themselves and should be a permissive policy, rather than preventative.

The CoC as a whole is a relatively new concept to the chat fora - there was a time where this didn't exist and we have since learnt from our mistakes.

**Comment by jsren** [comment]
@Boltovnya 
> When people aggressively argue for language X over language Y, it can become, for lack of a better phrase, a s**t flinging contest. In these situations, the conversation becomes exclusionary to those who do want to get involved and in turn ruins the community spirit of Compsoc and its associated chat rooms.

That's great - put that in the CoC.

> Codes of conduct are a way of informing new people on how they should expect to conduct themselves

Absolutely, sorry I should have made it clearer when I said 'preventative' that I meant people knowing in advance how to conduct themselves.

> Outlining specific examples is a good method of enforcing better behaviours for discussion, and I don't agree that this should change.

Absolutely. I believe that it should be more specific and show how the examples are bad and can be used negatively, rather than suggesting that all sarcastic questions are bad and that all "fanboy-ism" is bad.

> should be a permissive policy

Again I agree. Our worries are that the examples given and the requirement "be nice" is too broad, and as a result the CoC could be easily used to overly police conversation.

**Comment by Boltovnya** [comment]
>rather than suggesting that all sarcastic questions are bad and that all "fanboy-ism" is bad.

The point here isn't that they're always bad - it's that even unintentionally it can come across as condescending and off-putting. And that's the issue it tries to address - motive and intent isn't everything.

**Comment by jsren** [comment]
@Boltovnya 
> even unintentionally it can come across as condescending and off-putting

We're not arguing over whether it's bad - we're arguing that this perspective is exactly what should be in a CoC, and isn't right now.

**Comment by lopcode** [comment]
I don't think this conversation was started constructively, and they are almost never constructive in PRs in my experience. I suggest @neanias or another admin locks it.

**Pull request closed without merging**
